name: shared
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  dio: ^5.7.0
  
  # Dependeny Injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # Local Storage
  shared_preferences: ^2.3.3

  # State Management
  flutter_bloc: ^8.1.6

  # UI
  iconsax: ^0.0.8
  flutter_svg: ^2.0.14
  skeletonizer: ^1.4.2
  lottie: ^3.1.3

  # Utils
  equatable: ^2.0.5
  collection: ^1.18.0

  # Modules
  core:
    path: ../core
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.3
  injectable_generator: ^2.6.2
