name: task
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Dependency Injection
  injectable: ^2.5.0

  # Utils
  json_annotation: ^4.9.0

  # Modules
  core:
    path: ../../../../core
  shared:
    path: ../../../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.3
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
