name: core
description: "Package for core functionalities"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Internationalization
  flutter_localizations:
    sdk: flutter

  # Routing
  go_router: ^14.6.0

  # Utils
  encrypt: ^5.0.3
  dartz: ^0.10.1
  collection: ^1.18.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.8.0
  build_runner: ^2.4.3

flutter:
  generate: true

